/* PRIMEIRA FORMA NORMAL

REGRAS:
1. TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA.
2. TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA.
QUANTO O CAMPO FOR DIVISÍVEL.
3. TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE
TODO O REGISTRO COMO SENDO ÚNICO. ISSO É O QUE CHAMAMOS DE CHAVE PRIMÁRIA
OU PRIMARY KEY. -> A CHAVE PRIMÁRIA IDENTIFICA UM REGISTRO INTEIRO (LINHA) COMO SENDO ÚNICO.
EXISTEM DOIS TIPOS DE CHAVES:
-> NATURAL - PERTENCE A ALGO NATURALMENTE (EX: CPF)
-> ARTIFICIAL - PERTENCE A ALGO ARTIFICIALMENTE (EX: ID)


NO EXEMPLO DA TABELA CLIENTE, TELEFONE É UM CAMPO MULTIVALORADO E ENDEREÇO TAMBÉM, ENTÃO
SÃO TABELAS DIFERENTES, ONDE CLIENTE POSSUI TELEFONE E CLIENTE POSSUI ENDEREÇO.
-> QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGÓCIO

EXEMPLO:
ESTAMOS NO INÍCIO DA MODELAGEM PARA UM SISTEMA E O NOSSO GESTOR NOS PEDIU A MODELAGEM DA TABELA
DE CLIENTES COM A SEGUINTE REGRA DE NEGÓCIO:
ENDERECO - OBRIGATÓRIO O CADASTRO DE UM ENDERECO (NO MÁXIMO 1). (1, 1)
TELEFONE - O CLIENTE NÃO É OBRIGADO A INFORMAR TELEFONE (0, N)
POREM, CASO QUEIRA, ELE PODE INFORMAR MAIS DE UM.

> CARDINALIDADE:
(0,N)
(0,1)
(1,N)
(1,1)
A PRIMEIRA COLUNA: OBRIGATORIEDADE (SE 0 É FALSO, SE 1 É VERDADEIRO)
A SEGUNDA COLUNA: CARDINALIDADE (CARDINALIDADE DEFINE O MÁXIMO: 1 OU MAIS DE 1)

> O ENDEREÇO PRECISA TER CLIENTE? SIM (1) - OBRIGATORIO
> QUANTOS CLIENTES PERTENCEM AO UM ENDEREÇO? 1 (1) - CARDINALIDADE
(1,1)

O RELACIONAMENTO DE CLIENTE E ENDEREÇO É 1X1, POIS UM CLIENTE PERTENCE A UM ENDEREÇO E É OBRIGATÓRIO UM CADASTRO DE ENDEREÇO.
A CARDINALIDADE DE ENDEREÇO É (1,1) E DE CLIENTE É (1,1), LOGO SELECIONA A SEGUNDA COLUNA DE CADA CARDINALIDADE.
ENTÃO, É UM RELACIONAMENTO DE 1 PARA 1.

 */

CREATE DATABASE COMERCIO;
USE COMERCIO;
SHOW DATABASES;

DROP TABLE CLIENTE; -- APAGAR CLIENTE

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,  -- INCREMENTAR O IDCLIENTE
	NOME VARCHAR (30) NOT NULL,  -- COLUNA NÃO PODE SER NULA 
	SEXO ENUM('M', 'F') NOT NULL, -- ENUM SÓ EXISTE EM MYSQL
	EMAIL VARCHAR(50) UNIQUE, -- EMAIL UNICOM NÃO PODE SE REPETIR
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR (30) NOT NULL,
	BAIRRO VARCHAR (30) NOT NULL,
	CIDADE VARCHAR (30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE, -- POIS O TIPO DA CHAVE PRIMARIA DE CLIENTE É INT. UNIQUE, POIS O RELACIONAMENTO É DE 1X1.
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

/* ENDERECO - OBRIGATÓRIO
CADASTRO DE SOMENTE UM.
TELEFONE - NÃO OBRIGATÓRIO
CADASTRO DE MAIS DE UM (OPCIONAL)*/

-- FOREIGN KEY (FK)--
/*É A CHAVE PRIMÁRIA DE UMA TABELA QUE VAI ATÉ OUTRA
TABELA PARA FAZER REFERÊNCIA ENTRE REGISTROS. */

/* 
-> EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA
-> EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA SEMPRE FICARÁ NA CARDINALIDADE N
*/